### ISSUE TITLE
Configure tinyColorPicker with a set of predefined colors

### ISSUE THREAD

**Issue by george3447** [PitPik/tinyColorPicker#17]
Is there any way to configure the color picker with predefined set of colors like the below image
![screen-shot-all](https://cloud.githubusercontent.com/assets/10616010/6938825/1741b6b2-d884-11e4-849e-260a7479e3ce.png)

**Comment by PitPik** [comment]
Hi @george3447 
in the `index.js` file there is a demo for the color memory tiles. Its configured in `plugin.memory` -> `.find('.cp-memory div').each(function() {...` but in the demo its driven by `Math.random`.
You can use something else instead of `random()`, even some data from cookies or local storage...
By the way, you seem to have an old version. Maybe you want to update your local copy.
