### ISSUE TITLE
Issue using jQuery Button

### ISSUE THREAD

**Issue by ScottDWagner** [PitPik/tinyColorPicker#23]
i have a button like below but i cant seem to get the color picker to work with it. What Happens is the color picker shows up in the bottom left corner of the screen instead of below the button.

<button id="TestButton"></button>

<script type="text/javascript">
      $(document).ready(function () {
          $('#TestButton').button({
                   text:false,
                   icons:{primary:'ui-icon-plus'}
           }).click(function (e) {
               e.preventDefault();
          }).colorPicker();
      })
</script>

**Comment by PitPik** [comment]
Hi @ScottDWagner,
thanks for your comment, but I have a hard time to understand what your issue is about:
"i have a button like below..." not clear wich button you're talking about...
If you want to use a `<div>` as a trigger for the color-picker then give it a className like `<div class="myDivs">` and init color-picker with `var myColorPicker = $('.myDivs').colorPicker();`

Send me a JSFiddle link with your setup, otherwise I have no chance to guess what you need or what your troubles are.
