### ISSUE TITLE
Sliders visible over colour palette in jquerymobile

### ISSUE THREAD

**Issue by sticilface** [PitPik/tinyColorPicker#38]
The slider pusher things are visible over the palette. 

This occurs in both safari, and chrome. 
![screenshot 2015-12-14 18 38 32](https://cloud.githubusercontent.com/assets/10061736/11790317/0959be58-a293-11e5-8400-5bdd0763c433.png)
![screenshot 2015-12-14 18 38 20](https://cloud.githubusercontent.com/assets/10061736/11790319/0c973370-a293-11e5-901b-2b5ed9da9df8.png)

**Comment by PitPik** [comment]
Hi @sticilface ,
first, I see that you're using an old version of tinyColorPicker (#NANNAN0A) ;o)... but
this is probably because you use jQuery mobile,... and they do some nasty stuff with z-index.
Just inspect the 'slider button' and see what z-index they set on it,... use the inline possibility of tinyColorPicker to add some css and put it over the sliders:

``` javascript
renderCallback: function($elm, toggled) {
    // you know this one already
},
cssAddon: '.cp-color-picker{z-index:16777271}'
// or 2147483647 is the highest in modern browsers
```

**Comment by PitPik** [comment]
BTW: would you mind clicking on the ★ if you like tinyColorPicker ;o)
Thanks

**Comment by sticilface** [comment]
Oh.. i only downloaded it from github yesterday!  will update.  

That worked great.  Many thanks :)

**Comment by sticilface** [comment]
consider yourself starred!
