### ISSUE TITLE
Incorrect behavior when initializing by wrapping element insteand of selector

### ISSUE THREAD

**Issue by emn178** [PitPik/tinyColorPicker#41]
Hi,

It can work by selector like this:

``` JavaScript
$('#color').colorPicker();
```

But it has problem by wrapping element like this

``` JavaScript
$($('#color')[0]).colorPicker();
```

Please refer to
https://jsfiddle.net/u9v08hbu/

**Comment by PitPik** [comment]
Hi @emn178 ,
thanks for your participation!
Well, you're right, tinyClorPicker doesn't accept elements but only selectors. This was a decision I made to keep things simple and small, but it's not quite jQuery conform to do so.
Even though in your case it wouldn't make a difference because `$('#color')` is one element anyhow (because it's a ID selector), the plugin should handle this. (You could also have something like `$('.color').eq(0).colorPicker()` and it wouldn't work either... but it should)

I will think this mechanism over and fix this as soon as possible.
Thanks a gain and Merry Christmas.
Cheers,
Peter

**Comment by PitPik** [comment]
Hi @emn178,
took quite a long time but now tinyColorPicker works as expected:

``` javascript
$('.color').eq(0).colorPicker(); // works now
$($('#color')[0]).colorPicker(); // works fine now

var elm = document.getElementById('color');
$(elm).colorPicker(); // just like expected by jQuery plugin
```

**Comment by emn178** [comment]
:+1:
