### ISSUE TITLE
Cannot figure out how to set callback for setColor()

### ISSUE THREAD

**Issue by patrickcorrigan** [PitPik/tinyColorPicker#58]
Hello PitPik, I'm trying to use your nice color picker but I cannot figure out how to get the value of the color selected. From reading I have figured out that I need to change the function setColor that belongs to the Colors object that belongs to ColorPicker().  What is the simplest way to update the callback function setColor?

**Comment by PitPik** [comment]
Hi @patrickcorrigan,
thanks for your interest in tinyColorPicker ;o)
I don't quite understand your question though...
- `setColor()` is a method from `Colors`, a module that calculates all kinds of color values. You don't need to change this method (you actually shouldn't ;o)
- if you want to use `setColor()` as you are about to manipulate the color by a different source (just like in the example with the RGB-sliders) then look at the example in ./demo/index.js on line 29 how it is done. `that.color.setColor({r: 200}, 'rgb');` sets the red value of the current color to 200. Next time the rendering will take place (`that.render();`), it will update your colorPicker with this value.
  Instead of `{r: 200};` you can change more than one part of the color or all like `{r: 200, g: 10, b: 33}`

You're actually writing "I cannot figure out how to get the value of the color selected", so you want to "read" something and then you ask: "...to update the callback function setColor". Maybe I miss understood you and didn't answer quite the way you expected. If that's the case, please let me know.

Cheers

**Comment by patrickcorrigan** [comment]
Hi @PitPik,
thank you for the quick and informative responses. Yes you are right what I actually want to say is that I can't figure out how to get the value of the color selected :P How do I do this. I feel ridiculous as I couldn't figure it out and had to ask you. Thank you in advance :)

**Comment by PitPik** [comment]
Hi @patrickcorrigan again,
I still don't know what you need to do. When do you need to read the color value. Is it in the ```renderCallback```? This is done by ```var colors = this.color.colors;```, there you get all the values you need,... or is it after you closed it, then you just need to either also use ```renderCallback``` or just read the value from the input field.
I need a bit more information (or code) to figure out what your problem is.
I make another wild guess:
I assume you choose a color and just closed the color picker:
```javascript
renderCallback: function($elm, toggled) {
    var colors = this.color.colors;

    if (toggled === true) { // this happens on open (first time or when switching to another one)
        if (this.$oldElement) { // previously closed while opening this one
            console.log(colors); // show color model of previously opened
        }
        this.$oldElement = $elm; // store for next switch...
    } else if (toggled === false) { // this happens on close (only)
        console.log(colors); // show color model of just closed
        this.$oldElement = null; // delete $oldElement as there is no other swich possible
    }
}
```

Does this help??

**Comment by PitPik** [comment]
Hi @patrickcorrigan again,
I still don't know what you need to do. When do you need to read the color value. Is it in the ```renderCallback```? This is done by ```var colors = this.color.colors;```, there you get all the values you need,... or is it after you closed it, then you just need to either also use ```renderCallback``` or just read the value from the input field.
I need a bit more information (or code) to figure out what your problem is.
I make another wild guess:
I assume you choose a color and just closed the color picker or switched to another one, so you might want to save your choice right after closing or switching (console.log demonstrates some action):
```javascript
renderCallback: function($elm, toggled) {
    var colors = this.color.colors,
        oldValue = '';

    if (toggled === true) { // this happens on open (first time or when switching to another one)
        if (this.$oldElement && this.$oldElement[0] !== $elm[0]) { // previously closed while opening this one
            oldValue = this.$oldElement.val(); // actual value of previous element
            oldValue = this.color.setColor(oldValue, this.$oldElement.data('colorMode')); // set color to that old value
            console.log(this.color.toString()); // show color of previously opened in rgba mode
        }
        this.$oldElement = $elm; // store for next switch...
    } else if (toggled === false) { // this happens on close (only)
        console.log(this.color.toString()); // show color model of just closed
        this.$oldElement = null; // delete $oldElement as there is no other swich possible
    }
}
```
Does this help??

**Comment by PitPik** [comment]
Hi @patrickcorrigan again,
I still don't know what you need to do. When do you need to read the color value. Is it in the `renderCallback`? This is done by `var colors = this.color.colors;`, there you get all the values you need,... or is it after you closed it, then you just need to either also use `renderCallback` or just read the value from the input field.
I need a bit more information (or code) to figure out what your problem is.
I make another wild guess:
I assume you choose a color and just closed the color picker or switched to another one, so you might want to save your choice right after closing or switching (console.log demonstrates some action):

``` javascript
renderCallback: function($elm, toggled) {
    var colors = this.color.colors,
        oldValue = '',
        helperColor = this.helperColor = this.helperColor || new this.color.constructor(); // new instance for converting colors

    if (toggled === true) { // this happens on open (first time or when switching to another one)
        if (this.$oldElement && this.$oldElement[0] !== $elm[0]) { // previously closed while opening this one
            oldValue = this.$oldElement.val(); // actual value of previous element
            helperColor.setColor(oldValue); // set color to that old value
            console.log(helperColor.toString()); // show color of previously opened in rgba mode
        }
        this.$oldElement = $elm; // store for next switch...
    } else if (toggled === false) { // this happens on close (only)
        console.log(this.color.toString()); // show color model of just closed
        this.$oldElement = null; // delete $oldElement as there is no other swich possible
    }
}
```

Does this help??

**Comment by PitPik** [comment]
Hi @patrickcorrigan,
Does the last example answer your questions and help you with your needs?
Please let me know if there is more you need to know.

See also `./demo/index.js` (in new updated files) for a slightly different solution.

Cheers,
Peter

**Comment by patrickcorrigan** [comment]
I'm terribly sorry for the late reply. Thank you so much for your response. Yes it solved my problem perfectly. Thank you so much. The only issue I have left is that after selecting a color there is a slight delay before the callback is executed. Is there any way to synchronously get the color. Thank you so much for your help.

**Comment by patrickcorrigan** [comment]
Should I set the color in the mousedown event instead?
