### ISSUE TITLE
Keep changes?

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#6]
I not sure this is a bug or a mistake from me. I use this code:

$('input.color').colorPicker({
    renderCallback: function($elm, toggled)
    {
        console.log($elm.text);
        $('#field').css('background-color', $elm.text);
    }
});

After close the colorpicker box the changed color in #field is removed. How I can stop this? Like the input field I want the color in #field too. ;)

Here a example: http://jsfiddle.net/030j27LL/1/
click on a input field, change color and close box. the field above lost background-color.

**Comment by PitPik** [comment]
I actually don't know: Haven't looked into this and never had it myself. So, for now: put a `if ($elm.text)` in front of your `$('#debug-a').text(...`

I try to fix this as soon as possible

**Comment by PitPik** [comment]
OK, I looked into this again. Maybe I should change this as it is a bit confusing.
$elm.text is actually an internal variable. It only carries a value if the value of the input field changed from the previous rendering (this is due to a better behavior of the input field and a faster rendering performance). If the value is the same as one step before, then this variable becomes empty to signal the renderer not to render anything here...
In this case you should use `$elm.val()` instead of `$elm.text`.
