### ISSUE TITLE
renderCallback not working with multiple instances?

### ISSUE THREAD

**Issue by Daijobou** [PitPik/tinyColorPicker#8]
I want create multiple instances of tinyColorPicker: http://jsfiddle.net/030j27LL/1/

But all changes going only to first callback.

**Comment by PitPik** [comment]
The color picker is only a single instance (due to memory usage and usually you don't need different behaviors on different input fields)...however, if you call .colorPicker() again, all the options are ignored, so you need to see what input field you chose inside your callback function to do different things.
See http://jsfiddle.net/030j27LL/2/ for what I mean...
Calling .colorPicker() again on a different selector, the selector result gets extended.
If you need a color picker with multiple instances, take the other color picker: https://github.com/PitPik/colorPicker

**Comment by Daijobou** [comment]
Thanks for that example and explain. :)
